version: '3'

services:
  nginx:
    image: codershisho/nginx:1.25.0
    container_name: nginx-${PROJECT_NAME}
    tty: true
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - node
  
  node:
    image: codershisho/node:18.18.0-alpine
    container_name: node-${PROJECT_NAME}
    tty: true
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      TZ: ${TIME_ZONE}
    ports:
      - ${NODE_PORT}:3000
      - 24678:24678 # HMR用のポートを追加
    volumes:
      - ${NOTE_MOUNT_FOLDER}:/var/www
    stdin_open: true
    restart: always
    depends_on:
      - php
  
  php:
    image: codershisho/php:8.2-fpm
    container_name: php-${PROJECT_NAME}
    tty: true
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ${PHP_MOUNT_FOLDER}:/var/www
    stdin_open: true
    restart: always
    environment:
      TZ: ${TIME_ZONE}

  db:
    image: mariadb:10.9
    container_name: mariadb-${PROJECT_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
volumes:
  db_data: